version: "3.8"
services:
  redis:
    image: redis:7
    container_name: axxon-redis
    ports:
      - "6379:6379"

  wsserver:
    build:
      context: .
      dockerfile: Dockerfile.ws # make a dedicated Dockerfile for WS
    container_name: axxon-ws
    environment:
      - REDIS_URL=redis://redis:6379
      - CLIENT_URL=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - redis
